// --------------------------------------------------------
// Code generated by Papyrus Java
// Corregido manualmente
// --------------------------------------------------------

package model;

import java.util.ArrayList;

public class Caretaker {

    private ArrayList<Comando> historial;
    private int apuntador;

    public Caretaker() {
        this.historial = new ArrayList<>();
        this.apuntador = -1;
    }

    public void ejecutar(Comando comando) {
        if (comando == null) {
            return;
        }

        while (historial.size() > apuntador + 1) {
            historial.remove(historial.size() - 1);
        }

        comando.ejecutar();
        historial.add(comando);
        apuntador++;
    }

    public void deshacer() {
        if (apuntador < 0) {
            return;
        }

        historial.get(apuntador).deshacer();
        apuntador--;
    }

    public void rehacer() {
        if (apuntador + 1 >= historial.size()) {
            return;
        }

        apuntador++;
        historial.get(apuntador).ejecutar();
    }

    public ArrayList<Comando> getHistorial() {
        return historial;
    }

    public int getApuntador() {
        return apuntador;
    }
}