// --------------------------------------------------------
// Code generated by Papyrus Java
// Corregido manualmente
// --------------------------------------------------------

package model;

public abstract class Comando {

    public Caretaker caretaker;

    public abstract void ejecutar();

    public abstract void deshacer();
}