// --------------------------------------------------------
// Code generated by Papyrus Java
// Corregido manualmente
// --------------------------------------------------------

package model;

public class ComandoRestar extends Comando {

    public MementoCalculadora mementoAnterior;
    public Calculadora receptor;
    public Calculadora calculadora;

    public ComandoRestar(Calculadora receptor) {
        this.receptor = receptor;
        this.calculadora = receptor;
    }

    @Override
    public void deshacer() {
        if (mementoAnterior != null) {
            receptor.setEstado(
                mementoAnterior.getValorActual(),
                mementoAnterior.getExpresion(),
                mementoAnterior.getMemoriaOp(),
                mementoAnterior.isEsperarOperando(),
                mementoAnterior.getOperacionPend()
            );
        }
    }

    @Override
    public void ejecutar() {
        mementoAnterior = receptor.Guardar();
        receptor.seleccionarOperacion("-");
    }
}