// --------------------------------------------------------
// Code generated by Papyrus Java
// Corregido manualmente
// --------------------------------------------------------

package model;

public class ComandoEquivalencia extends Comando {

    public Calculadora receptor;
    public MementoCalculadora mementoAnterior;
    public Calculadora calculadora;

    public ComandoEquivalencia(Calculadora receptor) {
        this.receptor = receptor;
        this.calculadora = receptor;
    }

    @Override
    public void ejecutar() {
        mementoAnterior = receptor.Guardar();
        receptor.equivalencia();
    }

    @Override
    public void deshacer() {
        if (mementoAnterior != null) {
            receptor.setEstado(
                mementoAnterior.getValorActual(),
                mementoAnterior.getExpresion(),
                mementoAnterior.getMemoriaOp(),
                mementoAnterior.isEsperarOperando(),
                mementoAnterior.getOperacionPend()
            );
        }
    }
}