// --------------------------------------------------------
// Code generated by Papyrus Java
// Corregido manualmente
// --------------------------------------------------------

package model;

public class ComandoDigitar extends Comando {

    public Calculadora receptor;
    public MementoCalculadora mementoAnterior;
    public String digito;
    public Calculadora calculadora;

    public ComandoDigitar(Calculadora receptor, String digito) {
        this.receptor = receptor;
        this.calculadora = receptor;
        this.digito = digito;
    }

    @Override
    public void deshacer() {
        if (mementoAnterior != null) {
            receptor.setEstado(
                mementoAnterior.getValorActual(),
                mementoAnterior.getExpresion(),
                mementoAnterior.getMemoriaOp(),
                mementoAnterior.isEsperarOperando(),
                mementoAnterior.getOperacionPend()
            );
        }
    }

    @Override
    public void ejecutar() {
        mementoAnterior = receptor.Guardar();
        receptor.ingresarDigito(digito);
    }
}