// --------------------------------------------------------
// Code generated by Papyrus Java
// Corregido manualmente
// --------------------------------------------------------

package model;

public class ComandoMultiplicar extends Comando {

    public Calculadora receptor;
    public MementoCalculadora mementoAnterior;

    public ComandoMultiplicar(Calculadora receptor) {
        this.receptor = receptor;
    }

    @Override
    public void ejecutar() {
        mementoAnterior = receptor.Guardar();
        receptor.seleccionarOperacion("*");
    }

    @Override
    public void deshacer() {
        if (mementoAnterior != null) {
            receptor.setEstado(
                mementoAnterior.getValorActual(),
                mementoAnterior.getExpresion(),
                mementoAnterior.getMemoriaOp(),
                mementoAnterior.isEsperarOperando(),
                mementoAnterior.getOperacionPend()
            );
        }
    }
}