// --------------------------------------------------------
// Code generated by Papyrus Java
// Corregido manualmente
// --------------------------------------------------------

package model;

public class MementoCalculadora {

    public boolean esperarOperando;
    public String expresion;
    public String memoriaOp;
    private Float valorActual;
    public String operacionPend;

    // Relaciones generadas desde el UML
    public ComandoEquivalencia comandoequivalencia;
    public ComandoDividir comandodividir;
    public ComandoMultiplicar comandomultiplicar;
    public ComandoRestar comandorestar;
    public ComandoSumar comandosumar;
    public ComandoDigitar comandodigitar;
    public ComandoBorrar comandoborrar;

    public MementoCalculadora(String memoriaOp, Float valorActual, boolean esperarOperando,
                              String expresion, String operacionPend) {
        this.memoriaOp = memoriaOp;
        this.valorActual = valorActual;
        this.esperarOperando = esperarOperando;
        this.expresion = expresion;
        this.operacionPend = operacionPend;
    }

    public void recuperar() {
        // Método dejado según el UML generado.
    }

    public Float getValorActual() {
        return valorActual;
    }

    public String getExpresion() {
        return expresion;
    }

    public String getMemoriaOp() {
        return memoriaOp;
    }

    public boolean isEsperarOperando() {
        return esperarOperando;
    }

    public String getOperacionPend() {
        return operacionPend;
    }
}